---
title: "Interactive Visualization"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r}
# Load libraries
library(rgeos)
library(shiny)
library(shinythemes)
library(leaflet.extras)
library(shinyWidgets)
library(rworldxtra)
library(rworldmap)
library(leaflet)
library(ggplot2)
library(tidyverse)
library(sf)
library(rvest)
library(stringr)
library(scales)
library(viridis)
library(plotly)
library(shiny)

# World map data
map <- getMap() 
# Read in CSV file with data for electricity access
electricity = read.csv('electricity.csv')
# Convert factors to character vectors
electricity$Entity = as.character(electricity$Entity)
electricity$Code = as.character(electricity$Code)
# Ensure country names in electricity.csv match the country
# names in map.world
electricity = electricity %>%  mutate(Entity = recode(Entity, 
                           `United States`
                            = 'USA',
                           `United Kingdom` 
                            = 'UK',
                            `United States Virgin Islands` 
                            = 'Virigin Islands',
                            `Democratic Republic of Congo` 
                            = 'Democratic Republic of the Congo',
                            `Trinidad and Tobago`
                            = 'Trinidad',
                            `Antigua and Barbuda`
                            = 'Antigua'
                        )
                   )
# Read in CSV file with data for renewable energy consumption
renewables = read.csv('renewables.csv')
renewables$Entity = as.character(renewables$Entity)
renewables$Code = as.character(renewables$Code)
renewables = renewables %>%  mutate(Entity = recode(Entity,                            `United States`
                            = 'USA',
                           `United Kingdom` 
                            = 'UK',
                            `United States Virgin Islands` 
                            = 'Virigin Islands',
                            `Democratic Republic of Congo` 
                            = 'Democratic Republic of the Congo',
                            `Trinidad and Tobago`
                            = 'Trinidad',
                            `Antigua and Barbuda`
                            = 'Antigua'
                        )
                   )
# Read in CSV file with data for human development index
hdi = read.csv('hdi.csv')
hdi$Entity = as.character(hdi$Entity)
hdi$Code = as.character(hdi$Code)
hdi = hdi %>%  mutate(Entity = recode(Entity,                                               `United States`
                            = 'USA',
                           `United Kingdom` 
                            = 'UK',
                            `United States Virgin Islands` 
                            = 'Virigin Islands',
                            `Democratic Republic of Congo` 
                            = 'Democratic Republic of the Congo',
                            `Trinidad and Tobago`
                            = 'Trinidad',
                            `Antigua and Barbuda`
                            = 'Antigua'
                        )
                   )
# Obtain data for longitutde and latitude coordinates of the
# centroids of every country
wmap = getMap(resolution='high')
centroids = gCentroid(wmap,byid=TRUE)
# Convert to data frame
centroids_df = as.data.frame(centroids)
# Country names become a separate column
centroids_df <- cbind(rownames(centroids_df), centroids_df)
rownames(centroids_df) <- NULL
colnames(centroids_df) <- c("country","long","lat")
# Ensure centroids_df has the same country names as the
# electricity, renewables, and hdi datasets
centroids_df = centroids_df %>%  mutate(country = recode(country,                                     `United States of America`
                                    = 'USA',
                                    `United Kingdom` 
                                    = 'UK',
                                   `United States Virgin Islands`
                                    = 'Virigin Islands',
                                   `Trinidad and Tobago` 
                                    = 'Trinidad',
                                   `Antigua and Barbuda` 
                                    = 'Antigua'
                                )
                          )
centroids_df$country = as.character(centroids_df$country)
# Left-join centroids_df and electricity
all_final = left_join(centroids_df,electricity,by = c('country' = 'Entity')) 
# Incorporate the data from renewables
all_final = left_join(all_final,renewables,by = c('country' = 'Entity','Code','Year'))
# Incorporate the data from hdi
all_final = left_join(all_final,hdi,by = c('country' = 'Entity','Code','Year'))
# Create a list of all unique countries shared by both the
# electricity dataset and centroids_df
featureList = intersect(unique(electricity$Entity),
                        unique(centroids_df$country))
```
    

Column {data-width=600}
-------------------------------------

### Map
```{r}
# Extract data for the year 2014 for plotting on the world map
sites = all_final[which(all_final$Year==2014),]
# Match values for the Access variable in sites with the 
# corresponding countries in map
map$access = sites[match(map$ISO3, sites$Code), "Access"]
# Match values for the Consumption variable in sites with the 
# corresponding countries in map
map$consumption = sites[match(map$ISO3, sites$Code), "Consumption"]
# Match values for the HDI_Full variable in sites with the 
# corresponding countries in map
map$hdi = sites[match(map$ISO3, sites$Code), "HDI_Full"]
# Palette
pal = colorBin(palette = "viridis", domain = map$access,
               bins = c(0,20,40,60,80,100))
# Information to display when hovering over a country
map$labels = paste0("<strong> Country: </strong> ", 
                  map$NAME, 
                  "<br/> ",
                  "<strong> % Electricity Access: </strong> ", 
                  round(map$access, 2),"%",
                  "<br/> ",
                  "<strong> % Renewable Energy: </strong> ", 
                  round(map$consumption, 2),"%",
                  "<br/> ",
                  "<strong> Human Development Index: </strong> ",
                  round(map$hdi, 2), 
                  "<br/>") %>%
                      lapply(htmltools::HTML)
# Use leaflet to add interactivity to the world map 
leaflet(map) %>% 
    addTiles() %>% 
    addProviderTiles("NASAGIBS.ViirsEarthAtNight2012") %>%
    setView(lng = 0, lat = 30, zoom = 2) %>%
    addPolygons(fillColor = ~pal(access),
                color = "white",
                fillOpacity = 0.7,
                label = ~labels,
                highlight = highlightOptions(
                            color = "black", 
                            bringToFront = TRUE)) %>%
    leaflet::addLegend(pal = pal, 
                       values = ~access, 
                       opacity = 0.7, 
                       title = "% Electricity Access")
```

Column {data-width=200}
-------------------------------------

### Chart
```{r}
# Interactivity via Shiny UI and Server
shinyApp(ui = fluidPage(
  # Set theme
  theme = shinytheme("spacelab"),
  # Explanatory text
  h2("SDG: Energy"),
  h4("Relationship between Energy and 
     Human Development Index (HDI)"),
  # User input determines what country data is graphed for
  selectInput(inputId = "featureInput1", label = "Select 
     Country", choices = featureList, selected = "Angola"),
  # Line Chart
  mainPanel(plotlyOutput("lineChart")
  )
),
  server = function(input,output) {
     # Convenience data frame for plot
     plot.df = reactive({all_final[which(all_final$country
                                   ==input$featureInput1),]})
     output$lineChart <- renderPlotly({
     # Line chart via plot_ly
     plot_ly(data=plot.df(), 
             name = '% Electricity Access', 
             x = ~Year, y = ~Access, 
             type = "scatter",mode = 'lines+markers') %>%
                 add_trace(y = ~Consumption, 
                           name = '% Renewable Energy',
                           mode = 'lines+markers') %>%
                 add_trace(y = ~HDI_Full*100, 
                           name = 'HDI',
                           mode = 'lines+markers') %>%
                 layout(legend = list(orientation = "h",   
                        xanchor = "center", 
                        x = 0.5, y=-0.2,
                        font = list(size = 10)),
                        yaxis = list(title = "Percent"),
                        margin=list(l = 5,r = 5,b = 5,t = 5))   
          })
})
```   
